openapi: 3.0.3

info:
  title: Schema for ServiceB
  version: 0.0.0
  description: >-

paths:

  /serviceb/:
    get:
      tags: [ServiceB]
      operationId: getAllItems
      description: return list of some items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './service_b.yaml#/components/schemas/ServiceB.Item'

  /serviceb/{item_id}:
    get:
      tags: [ServiceB]
      operationId: getSingleItem
      description: return single item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './service_b.yaml#/components/schemas/ServiceB.Item'

  /serviceb/{item_id}/{level_2}:
    get:
      tags: [ServiceB]
      operationId: getSingleItemLevel2
      description: return single item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
        - in: path
          name: level_2
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './service_b.yaml#/components/schemas/ServiceB.Item'
