name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements.txt

      - name: Run unit tests
        run: |
          sudo ${{ env.pythonLocation }}/python -m pytest -v -s

      - name: Generate python sdist and wheel distributions
        run: |
          python setup.py sdist --formats=gztar bdist_wheel --universal

      - name: Get all changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Output changed files
        id: changed_files
        run: echo ${{steps.file_changes.outputs.files_modified}}

      - name: Upload Assets to Pypi
        if: true == contains(steps.file_changes.outputs.files_modified, 'VERSION')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*